# Which kind of Fortran Compiler to use, gnu or ibm ?
compiler = intel
#compiler = cray

# Compilation option
__MPI = yes
__OMP = yes
__DEBUG = no
__FFT = no 

DIR_OBJ=.obj
DIR_MOD=.mod
DIR_EXE=bin

# Use FFTW library?
ifeq (${__FFT},yes)
   FFTW=
   INCFFT =
   LIBFFT = -lfftw3f -Wl,-rpath=${LD_RUN_PATH}
#   LIBFFT = -lfftw3f -Wl,--rpath -Wl,${LD_RUN_PATH} -Wl,--disable-new-dtags
else
   INCFFT =
   LIBFFT =
endif

# INTEL Fortran Compiler
ifeq (${compiler},intel)
  # Use MPI?
  ifeq (${__MPI},yes)
    FCC = mpif90
    CC = cc
  else
    FCC = mpif90
  endif

  # Use OpenMP?
  ifeq (${__OMP},yes)
 #   FLAGOMP = -fopenmp
    FLAGOMP = -qopenmp -axCORE-AVX2
#    FLAGOMP = -qopenmp -axCORE-AVX2 -g -traceback -check all -check bounds
  else
    FLAGOMP =
  endif

  # DEBUG?
  ifeq (${__DEBUG},yes)
    F90FLAGS =-O0 $(FLAGOMP) -traceback -check bounds -c -xP -fpp -fno-fnalias -fno-alias -ip -fomit-frame-pointer -ftz -assume byterecl -module $(DIR_MOD) -vec-report1 -mkl 
    CCFLAGS = -O0 $(FLAGOMP) -c 
    LDFLAGS  =-O0 -w $(FLAGOMP) -mkl
  else
#    F90FLAGS =-O3 $(FLAGOMP) -c -fpp -fp-model fast=2 -fno-fnalias -ansi-alias -fno-alias -fomit-frame-pointer -ftz -assume byterecl -module $(DIR_MOD) -vec-threshold0 -qopt-report -qopt-report-phase=VEC -mkl -I/opt/intel/composer_xe_2015.2.164/mkl/include/fftw/
#    CCFLAGS = -O3 $(FLAGOMP) -c -fp-model fast=2 -vec-threshold0 -qopt-report -qopt-report-phase=VEC -I/opt/intel/composer_xe_2015.2.164/mkl/include/fftw/
#    LDFLAGS  =-O3  $(FLAGOMP) -mkl -I/opt/intel/composer_xe_2015.2.164/mkl/include/fftw/
# petrichor
#    F90FLAGS =-O2 $(FLAGOMP) -c -fpp -fno-fnalias -ansi-alias -fno-alias -fomit-frame-pointer -ftz -assume byterecl -module $(DIR_MOD) -vec-threshold0 -qopt-report -qopt-report-phase=VEC -mkl -Wl,--rpath -Wl,${LD_RUN_PATH} -Wl,--disable-new-dtags
#    CCFLAGS = -O2 $(FLAGOMP) -c -vec-threshold0 -qopt-report -qopt-report-phase=VEC -Wl,--rpath -Wl,${LD_RUN_PATH} -Wl,--disable-new-dtags
#    LDFLAGS  =-O2 $(FLAGOMP) -mkl -Wl,--rpath -Wl,${LD_RUN_PATH} -Wl,--disable-new-dtags
    F90FLAGS = -O3 -fPIC $(FLAGOMP) -c -assume byterecl -module $(DIR_MOD) -mkl -Wl,--rpath -Wl,${LD_RUN_PATH} 
    CCFLAGS = -O3 -fPIC $(FLAGOMP) -c -Wl,--rpath -Wl,${LD_RUN_PATH}
    LDFLAGS  = -O3 -fPIC $(FLAGOMP) -mkl -Wl,--rpath -Wl,${LD_RUN_PATH} 
#    F90FLAGS =-O3 -ip $(FLAGOMP) -c -fpp -fp-model fast=2 -fno-fnalias -ansi-alias -fno-alias -fomit-frame-pointer -ftz -assume byterecl -module $(DIR_MOD) -vec-threshold0 -qopt-report -qopt-report-phase=VEC -mkl -Wl,-rpath=${LD_RUN_PATH}
#    CCFLAGS = -O3 -ip $(FLAGOMP) -c -fp-model fast=2 -vec-threshold0 -qopt-report -qopt-report-phase=VEC -Wl,-rpath=${LD_RUN_PATH}
#    LDFLAGS  =-O3 -ip  $(FLAGOMP) -mkl -Wl,-rpath=${LD_RUN_PATH}
  endif

  ## Good Performance
  #F90FLAGS =-O3 $(FLAGOMP) -c -fpp -fp-model fast=2 -fno-fnalias -ansi-alias -fno-alias -fomit-frame-pointer -ftz -assume byterecl -module $(DIR_MOD) -vec-threshold0 -opt-report -opt-report-phase=VEC -mkl
  #CCFLAGS = -O3 $(FLAGOMP) -c -fpp -fp-model fast=2 -vec-threshold0 -opt-report -opt-report-phase=VEC
  ## Good Performance
  #LDFLAGS  =-O3  $(FLAGOMP) -mkl

endif

# Cray Fortran Compiler
ifeq (${compiler},cray)
  # Use MPI?
  ifeq (${__MPI},yes)
    FCC = mpiifort
    CC = cc
  else
    FCC = mpiifort
  endif

  # Use OpenMP?
  ifeq (${__OMP},yes)
    FLAGOMP = -homp
  else
    FLAGOMP =
  endif

    F90FLAGS =-O3 -hfp3 $(FLAGOMP) -c $(DIR_MOD) -h vector3 -rm -Oipa4 -e m -J $(DIR_MOD) -I/opt/cray/fftw/3.3.4.4/haswell/include/fftw3/
    CCFLAGS = -O3 -hfp3 $(FLAGOMP) -c -h vector3 -hlist=a -hipa4 -I/opt/cray/fftw/3.3.4.4/haswell/include/fftw3/
    LDFLAGS  =-O3  -hfp3 $(FLAGOMP) -h vector3 -rm -I/opt/cray/fftw/3.3.4.4/haswell/include/fftw3/

endif

